### PR TITLE
Add copyright statements to Dockerfiles

### PR DESCRIPTION
**Pull request by gblewis1**

### CODE REVIEW

**Comment by gblewis1** [comment]
@nmgaston @tsirlapu please review

**Comment by nmgaston** [comment]
@gblewis1 - I believe the copyright is supposed to be from when they were created until the current year.  I'm not sure when these were created, but probably something like 2020-2023.

**Comment by gblewis1** [comment]
> @gblewis1 - I believe the copyright is supposed to be from when they were created until the current year. I'm not sure when these were created, but probably something like 2020-2023.

They were first published as open source in 2021 so I'll use that date.

**Comment by gblewis1** [comment]
@nmgaston changed copyrights.. please re-review

**Review by nmgaston — APPROVED** [review]

**Review by tsirlapu — APPROVED** [review]

**Pull request merged**
