### PR TITLE
Add missing symlink checks for cloudadapter

### PR DESCRIPTION
**Pull request by gblewis1**

### CODE REVIEW

**Comment by gblewis1** [comment]
@nmgaston Can you review? Still getting it through the integration test. Also please note there's a second commit that does autopep8 and introduces a lot of noise so it may be easier to review the first commit.

**Comment by nmgaston** [comment]
Generally I disagree with adding the # pragma: no cover.  A lot of those look like easy unit test cases.  With this being a scripted language, it seems important not to use ways to not create unit tests.

**Comment by gblewis1** [comment]
> Generally I disagree with adding the # pragma: no cover. A lot of those look like easy unit test cases. With this being a scripted language, it seems important not to use ways to not create unit tests.

@nmgaston My reasoning is that symlink checks touch the filesystem so are not suitable for unit tests.

**Review by nmgaston — APPROVED** [review]

**Comment by gblewis1** [comment]
unit tests added and PR approved

**Pull request merged**
