### PR TITLE
[NEXMANAGE-899] Fix dispatcher not recording state file and causing snapshot failure

### PR DESCRIPTION
**Pull request by yengliong93**
### PULL DESCRIPTION

The dispatcher agent raises an exception when it fails to retrieve the state value from the state file. This results in the dispatcher not recording the restart_reason and snapshot_num, which are important for the rollback scenario.
This PR removes the exception that occurs when the dispatcher agent is unable to retrieve the state value from the state file. In cases where the state is None, the dispatcher will still record the restart_reason and snapshot_num.

### Impact Analysis

| Info | Please fill out this column |
| ------ | ----------- |
| Root Cause | Dispatcher not records the restart_reason and snapshot_num. |
| Jira ticket | NEXMANAGE-899 |

### CODE MAINTAINABILITY

- [ ] Added required new tests relevant to the changes
- [ ] Updated Documentation as relevant to the changes
- [ ] PR change contains code related to security
- [ ] PR introduces changes that break compatibility with other modules/services (If YES, please provide description)
- [ ] Run `go fmt` or `format-python.sh` as applicable
- [x] Update Changelog
- [x] Integration tests are passing
- [ ] If Cloudadapter changes, check Azure connectivity manually

# _Code must act as a teacher for future developers_

### CODE REVIEW

**Comment by gblewis1** [comment]
Would like to see integration test passing -- will try triggering it later (Jenkins is down now).

**Comment by gblewis1** [comment]
@yengliong93 this looks good but I would like to run it through integration test first.

**Comment by gblewis1** [comment]
Both build and integration tests are blocked by Penang power outage.

**Review by gblewis1 — APPROVED** [review]

**Comment by yengliong93** [comment]
IT is failing. Checking it...

**Comment by yengliong93** [comment]
Unit tests fix and IT pass.

**Pull request merged**
