### PR TITLE
[NEXMANAGE-906] Truncate granular log instead of removing it

### PR DESCRIPTION
**Pull request by yengliong93**
### PULL DESCRIPTION

The dispatcher agent is unable to remove the granular log file in a read-only system. This PR modifies the dispatcher agent so that it truncates the file instead of removing it.

### Impact Analysis

| Info | Please fill out this column |
| ------ | ----------- |
| Root Cause | Specifically for bugs, empty in case of no variants |
| Jira ticket | Add the name to the Jira ticket eg: "NEXMANAGE-622". Automation will do the linking to Jira |

### CODE MAINTAINABILITY

- [ ] Added required new tests relevant to the changes
- [ ] Updated Documentation as relevant to the changes
- [ ] PR change contains code related to security
- [ ] PR introduces changes that break compatibility with other modules/services (If YES, please provide description)
- [ ] Run `go fmt` or `format-python.sh` as applicable
- [x] Update Changelog
- [ ] Integration tests are passing
- [ ] If Cloudadapter changes, check Azure connectivity manually

# _Code must act as a teacher for future developers_

### CODE REVIEW

**Comment by yengliong93** [comment]
@gblewis1 please have a review, thanks.

**Comment by gblewis1** [comment]
Would like to run this through integration test, but Jenkins seems to be down. Will check later.

**Comment by gblewis1** [comment]
Jenkins still down due to Penang power outage.  Approved, but need integration test first.

**Review by gblewis1 — APPROVED** [review]

**Comment by yengliong93** [comment]
Integration tests pass.

**Pull request merged**
