### PR TITLE
Improve/speed integration reloaded test for INBM

### PR DESCRIPTION
**Pull request by gblewis1**
- Print a better error message when DOCKER_USERNAME and DOCKER_PASSWORD are not set
- Pull in proxy from environment instead of using hardcoded proxy-chain.intel.com.

### CODE REVIEW

**Comment by lab-bldmstr** [comment]
Jenkins CI Status: FAILED & Jenkins log: https://cbjenkins-pg.devtools.intel.com/teams-iotgdevops01/job/iotgdevops01/job/ESC/job/ARUN/job/IntegrationReloaded-slow-UB_20.04/11/console & Verification Build  :  FAILED

**Comment by lab-bldmstr** [comment]
Jenkins CI Status: FAILED & Jenkins log: https://cbjenkins-pg.devtools.intel.com/teams-iotgdevops01/job/iotgdevops01/job/ESC/job/ARUN/job/IntegrationReloaded-slow-UB_20.04/13/console & Verification Build  :  FAILED

**Comment by lab-bldmstr** [comment]
Jenkins CI Status: FAILED & Jenkins log: https://cbjenkins-pg.devtools.intel.com/teams-iotgdevops01/job/iotgdevops01/job/ESC/job/ARUN/job/IntegrationReloaded-slow-UB_20.04/15/console & Verification Build  :  FAILED

**Comment by gblewis1** [comment]
@nmgaston @tsirlapu Please review. This passes integration testing.  I rebuilt the 20.04 image and tweaked some mirrors/proxy settings to (I hope) avoid further timeouts.

**Review by nmgaston — APPROVED** [review]

**Pull request merged**
