### PR TITLE
Update packages' version in requirement

### PR DESCRIPTION
**Pull request by yengliong93**
### PULL DESCRIPTION

Update packages' version in requirement to fix the BDBA issues.

### Impact Analysis

| Info | Please fill out this column |
| ------ | ----------- |
| Root Cause | Specifically for bugs, empty in case of no variants |
| Jira ticket | Add the name to the Jira ticket eg: "NEXMANAGE-622". Automation will do the linking to Jira |

### CODE MAINTAINABILITY

- [ ] Added required new tests relevant to the changes
- [ ] Updated Documentation as relevant to the changes
- [ ] PR change contains code related to security
- [ ] PR introduces changes that break compatibility with other modules/services (If YES, please provide description)
- [ ] Run `go fmt` or `format-python.sh` as applicable
- [ ] Update Changelog
- [ ] Integration tests are passing
- [ ] If Cloudadapter changes, check Azure connectivity manually

# _Code must act as a teacher for future developers_

### CODE REVIEW

**Comment by gblewis1** [comment]
@yengliong93 Which BDBA issues is this addressing? In our last scan of Turtle Creek we were able to triage out all the BDBA issues as they corresponded to up-to-date Ubuntu 20.04 provided C libraries pulled in by our build process.

**Comment by yengliong93** [comment]
> @yengliong93 Which BDBA issues is this addressing? In our last scan of Turtle Creek we were able to triage out all the BDBA issues as they corresponded to up-to-date Ubuntu 20.04 provided C libraries pulled in by our build process.

@gblewis1  It fixed one zlib 1.3 medium vulnerabilities issue.  
Before updating the package: https://bdba001.icloud.intel.com/#/product/5683287/analysis
After updating the package: https://bdba001.icloud.intel.com/#/product/5717040/analysis

**Comment by gblewis1** [comment]
> > @yengliong93 Which BDBA issues is this addressing? In our last scan of Turtle Creek we were able to triage out all the BDBA issues as they corresponded to up-to-date Ubuntu 20.04 provided C libraries pulled in by our build process.
> 
> @gblewis1 It fixed one zlib 1.3 medium vulnerabilities issue. Before updating the package: https://bdba001.icloud.intel.com/#/product/5683287/analysis After updating the package: https://bdba001.icloud.intel.com/#/product/5717040/analysis

sounds good then.. could you run this through integration testing?

**Comment by yengliong93** [comment]
Integration test is failing. Need to investigate...

**Comment by yengliong93** [comment]
Integration test is passing now.

**Review by gblewis1 — APPROVED** [review]

**Pull request merged**
